const codePromo = require('./codePromo.route')
const addPoint = require('./addPoint.route')
const getTokenBO = require('./getTokenBO.route')
const account = require('./account.route')
const randomCode = require('./randomCode.route')
const checkAuth = require('./checkAuth.route')
const getMemberBO = require('./getMemberBO.route')
const findMemo = require('./findMemo.route')
const deposit = require('./depositToken.router')
const getTimeZone = require('./getTimeZone.route')
const changePass = require('./changePass.router')
const ipfp = require('./ipfp.route')
const getClientIPFP = require('./getClientIPFP.route')
const client = require('./client.route')
const find_ID_ticket = require('./find_ID_ticket.route')
const game_categories = require('./game_categories.router')
const add_point_bo = require('./add_point.route')
const check_ve_gop = require('./check_ve_gop.route')
const get_timeZone = require('./get_timeZone.route')
const get_member_BO = require('./get_member_BO.route')
const get_token_BO = require('./get_token_BO.router')

module.exports = (app) => {{
    app.use('/code', codePromo)
    app.use('/add-point', addPoint)
    app.use('/get-token-bo', getTokenBO)
    app.use('/account', account)
    app.use('/generate-code', randomCode)
    app.use('/checkAuth', checkAuth)
    app.use('/getMemberBO', getMemberBO)
    app.use('/find-memo', findMemo)
    app.use('/deposit', deposit)
    app.use('/get-time-zone', getTimeZone)
    app.use('/change-pass', changePass)
    app.use('/ipfp', ipfp)
    app.use('/get-client-ipfp', getClientIPFP)
    app.use('/client', client)

    //-------V2-------
    app.use('/find-id-ticket', find_ID_ticket)
    app.use('/game-categories', game_categories)
    app.use('/add-point-bo', add_point_bo)
    app.use('/check-ve-gop', check_ve_gop)
    app.use('/get-timeZone', get_timeZone)
    app.use('/get-member-bo', get_member_BO)
    app.use('/get-token-bo', get_token_BO)
}}